spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/DarkRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bloggheaven
    username: root
    password: 33663366

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

server:
  port: 9090

jwt:
  auth:
    converter:
      resource-id: bloggheaven
      principle-attribute: preferred_username
